# Using the node alpine image to build the React app
image: node:8.10.0

variables:
  PUBLIC_URL: /superhafiz

cache:
  paths:
  - node_modules

stages:
- test-changes

pages:
  stage: test-changes
  script:
    - npm install # Install all dependencies
    - npm run build --prod # Build for prod
    - cp public/index.html public/404.html 
    - mv public _public
    - mv build public

artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
only:
    - development # Only run on master branch
