image: node:8.10.0

variables:
  PUBLIC_URL: /superhafiz
cache:
  paths:
  - node_modules

stages:
- test
- deploy

test :
  stage : test
  script:
   - npm install
   - npm run build --prod # Build for prod
   - cp public/index.html public/404.html 
    - mv public _public
    - mv build public
  artifacts:
    paths:
    - public
  only :
   - merge_requests

deploy:
  stage : deploy
  script:
    - npm install # Install all dependencies
    - npm run build --prod # Build for prod
    - cp public/index.html public/404.html 
    - mv public _public
    - mv build public
  artifacts:
    paths:
    - public
  only :
    - master

